site_name: 数院自救指南
site_url: https://mathselfsaving.cn/
site_author: hengyu0510
site_description: >-
  数院自救指南

repo_name: math-self-saving
repo_url: https://github.com/hengyu0510/math-self-saving/

copyright: Copyright &copy; 2021-present <a href="https://github.com/hengyu0510" target="_blank" rel="noopener noreferrer">hengyu0510</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  logo: images/logo-mark.svg
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes

plugins:
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: math-self-saving
          nav_translations:
            首页: Home
            数学分析: Mathematical Analysis
            高等代数: Advanced Algebra
            概率统计: Probability and Statistics
            实变函数: Real Analysis
            泛函分析: Functional Analysis
            拓扑学: Topology
            数值分析: Numerical Analysis
            最优化: Optimization
            数学工具: Mathematical Tools
  - search:
      lang:
        - zh
        - en
  - git-revision-date:
  - minify:
      minify_html: true
  - open-in-new-tab:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hengyu0510/math-self-saving/
nav:
  - 首页: index.md
  - 数学分析: 数学分析/index.md
  - 高等代数: 高等代数/index.md
  - 概率统计: 概率统计/index.md
  - 实变函数: 实变函数/index.md
  - 泛函分析: 泛函分析/index.md
  - 拓扑学: 拓扑学/index.md
  - 数值分析: 数值分析/index.md
  - 最优化: 最优化/index.md
  - 数学工具: 数学工具/index.md
